language: php

php:
    - 5.6
    - 7.0
    - 7.1

services:
  - redis-server
  - memcached

before_script:
    - composer install
    - php tests/Queue/run-queue-app-with-file-cache-driver.php &
    - php tests/Queue/run-queue-app-with-redis-cache-driver.php &
    - php tests/Queue/run-queue-app-with-memcached-cache-driver.php &

script:
  - vendor/bin/phpunit